repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        args:
          - --quiet
  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        # exclude: >-
        #   ^(.*comments_backup\.csv|.*poetry.lock)$
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        files: "aiohttp_msal/.*.py"
        additional_dependencies: ["types-redis"]
